
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mincpm-llama3-v2_5:$(date +%s)

    - name: Tag Docker image
      run: docker tag mincpm-llama3-v2_5:$(date +%s)  nemesis55/mincpm-llama3-v2_5:latest

    - name: Push Docker image to Docker Hub
      run: docker push  nemesis55/mincpm-llama3-v2_5:latest
