name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: nemesis55
        password: sksingh55

    - name: Build the Docker image
      id: build
      run: |
        TIMESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag mincpm-llama3-v2_5:$TIMESTAMP
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

    - name: Tag Docker image
      run: |
        docker tag mincpm-llama3-v2_5:$TIMESTAMP nemesis55/mincpm-llama3-v2_5:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push nemesis55/mincpm-llama3-v2_5:latest
